aml-development/ozp-hud

app/js/components/header/helpmodal.jsx
package.json

@arw180, @wski Please have a look.

fix(Docs and Videos): Added docs and videos links to help modal #278

---

app/js/components/header/index.jsx

this is specific to IE for some reason

fix(Global Nav): Fixed missing `/` in various links for center

---

app/js/api/Library.js
app/js/store/Library.js

OZBE8 = ozone-development/ozp-backend#8

feat(bookmarks): Bookmark removal works OZBE8

---

app/js/components/header/index.jsx
app/styles/_header.scss
package.json

Incorporated link into IA, added new icons to distinguish Contact Help
Desk and Submit Feedback, added hover styling for Submit Feedback,
updated Package.json to pull current icons repo (ozp-icons)

update (styling): #116 Updated "Contact Help Desk" link

---

app/js/main.js

This change adds reporting of metrics to the metrics server

Adding support for metrics

---

app/js/components/HudContactsWindow.jsx
app/js/components/header/index.jsx
app/js/main.js

Removed 'Help' and 'Feedback' links in the Navbar and replaced them with a 'Contact' link to leads to a modal containing all forms of contact.

Contacts modal

---

app/js/components/header/index.jsx
app/styles/_header.scss
app/styles/_library.scss
app/styles/_loadmask.scss
app/styles/_search.scss
app/styles/_variables.scss
app/styles/main.scss
app/styles/modal.scss

Removed a lot of unnecessary custom CSS in HUD. Just double check that everything still looks normal, mostly in the navbar.

fix(style): Clean up custom CSS, revert to default bootstrap

---

app/js/components/header/helpmodal.jsx

Clean up styling, layout, and language to maintain consistency on the Help Modal across the platform.

Help modal styling

---

app/js/components/header/helpmodal.jsx

fix(Auth): Help modal authentication

---

app/js/components/folder/FolderModal.jsx
app/js/components/header/helpmodal.jsx
app/styles/main.scss

This branch is parallel with the `white-modals` branch on ozp-bootstrap-sass. Waiting to push that until approved in HUD/Webtop.

Light-themed bootstrap modals

---

package.json

chore(package.json): Update Webpack to support npm v3

---

app/js/components/header/helpmodal.jsx

fix(Help): Fixed invalid role for appsmall stewards

---

app/js/main.js

Redirect users below IE10 away

Added browser detection to HUD

---

app/styles/main.scss

fix(home):added overflow-y: scroll; to main css

---

app/js/actions/Library.js
app/js/api/Library.js
app/js/components/folder/Add.jsx
app/js/components/folder/FolderModal.jsx
app/js/components/library/FolderTile.jsx
app/js/components/library/index.jsx
app/js/main.js
app/js/store/FolderLibrary.js
app/js/store/Library.js
app/js/util/RandomBase16.js

@clarkjefcoat @tonyalletag 
Checkout my branch, start hud, and click the manate below.
[![Foo](https://media.giphy.com/media/8LbsCQdh3cuQ/giphy.gif)](
http://localhost:8088/dist/#/add/New%20Folder/%22%5B%7B%5C%22id%5C%22:52,%5C%22entryid%5C%22:15%7D,%7B%5C%22id%5C%22:79,%5C%22entryid%5C%22:16%7D,%7B%5C%22id%5C%22:23,%5C%22entryid%5C%22:17%7D%5D%22)
it should add `Frame It 1`, `Clipboard 1` and `Chatterbox 1`. You need to be running on `ci-latest`. The shared link will be deponent on the backend a user is using.
It's worth noting this is kind of hacked in, backend changes will be required for a reliable method of doing this.

feat(Shared Folders): Hud share folders to other people

---

app/js/actions/Library.js

removed the close menu from js libary

---

app/js/components/folder/FolderTitle.jsx
app/js/components/library/FolderTile.jsx

to fix bug #125 
@wski @rkenyon1969 @clarkjefcoat @mannyrivera2010

Akonsowski 125

---

app/js/actions/Library.js
app/js/api/Library.js
app/js/components/folder/FolderModal.jsx
app/js/components/header/index.jsx
app/js/store/FolderLibrary.js

@rkenyon1969 @mannyrivera2010 @akonsowski

feat(SharedFolders): Add functionality for shared folders

---

app/js/components/header/index.jsx

[#708](https://github.com/aml-development/ozp-center/issues/708)
@rkenyon1969  @wski @blynch11p

fix(index):some menu options will not show up for second party users

---

app/js/api/Library.js
app/js/components/header/index.jsx
app/js/components/library/index.jsx
app/js/store/Library.js
app/js/tour/tour.js

Hud Ordering of Icons
Please Review
@blynch11p 
@lsemesky

feat(order): Introduced Ordering of Icon #231

---

app/js/components/header/helpmodal.jsx

@lsemesky @mannyrivera2010 @blynch11p

fix(tour):changed verbage from hud tour to tour

---

app/js/api/Library.js

added in a fix for the blank string that users enter not being valid

---

app/js/actions/Library.js
app/js/api/Library.js
app/js/components/library/FolderTile.jsx
app/js/components/library/LibraryTile.jsx
app/js/store/FolderLibrary.js
app/styles/_library.scss

@akonsowski @blynch11p 
Requires to pull master backend branch
the intent is to delete an entire bookmark folder for a user

enhance(hud): added drop down with action to delete folder

---

app/js/store/Library.js

made it so bookmarks of same app are not removed in ui

---

app/js/components/header/notificationsmodal.jsx

Please Review:
@lsemesky 
@mleeBoeing 
@blynch11p

feat(notification): Fixed link in notification model

---

app/js/components/header/index.jsx
app/styles/_header.scss
package.json

need to use the ozp-react-commons#notificationRefactor in this to test

updating modal to use shared react-commons notification modal

---

app/js/api/Library.js
app/js/store/Library.js
app/js/tour/hudTour.js

Initial test is pulling the code and verifying the warning in the HUD server are not showing.  
But also verify functionality of modified areas: HUD Tour Displays, Error messages for incorrect shared folders.
@lsemesky @rkenyon1969 @mleeBoeing @mannyrivera2010

Making changes in files to remove the compilation warnings in HUD

---

app/js/tour/hudTour.js

Fixing the spelling of 'separate'. (JIRA-799)

Spelling fix in Tour
